const fs = require("fs");
const axios = require("axios");

const username = "siddhartha-pradhan";

const getGitHubStats = async () => {
  const headers = {
    Accept: "application/vnd.github.v3+json",
    "User-Agent": "dynamic-readme-script"
  };

  const user = await axios.get(`https://api.github.com/users/${username}`, { headers });
  const repos = await axios.get(`https://api.github.com/users/${username}/repos?per_page=100`, { headers });

  let stars = 0;
  repos.data.forEach(repo => {
    stars += repo.stargazers_count;
  });

  return {
    followers: user.data.followers,
    publicRepos: user.data.public_repos,
    stars: stars
  };
};

const calculateUptime = () => {
  const birthDate = new Date("2002-09-13");
  const now = new Date();
  const diff = new Date(now - birthDate);
  return {
    years: diff.getUTCFullYear() - 2002,
    months: diff.getUTCMonth(),
    days: diff.getUTCDate()
  };
};

const generateREADME = async () => {
  const { followers, publicRepos, stars } = await getGitHubStats();
  const { years, months, days } = calculateUptime();

  const readme = `<!-- README generated by readme.js. If you're reading this raw, congrats. You're early. -->

\`\`\`
Siddhartha / README.md
\`\`\`

\`\`\`
(c) . - . (c)        System.OS     : A black-box dev environment where code is crafted first, polished later. Built on silent documentation dives, dockerized dreams, and dark mode discipline.
( ⚆ _ ⚆ )           System.Uptime : ${years} years, ${months} months, ${days} days old
 / (_) \\            Location      : Kathmandu, Nepal
/_/   \\_\\          Status        : Grooving in Full Stack Flow™

Technologia Stack
  • Languages         : C#, TypeScript, Python, JavaScript
  • Frameworks        : .NET, React, Blazor, Django
  • Tools             : Docker, GitHub Actions, Hangfire, Firebase, Stripe
  • DB Love           : PostgreSQL, SQL Server, Redis
  • Other Skills      : CI/CD, API Development, Third-Party Integrations

GitHub Stats
  • Public Repositories : ${publicRepos}
  • Stars Collected     : ${stars}
  • Followers           : ${followers}
  • Lines of Code       : 3.1M++ (and counting...)

Currently Cooking
  • A fully dockerized dream that works on *your* machine too.
  • CI/CD pipelines that don’t randomly break at 2AM.
  • An API so clean it passes Lint with compliments.
  • C# and JS logic that doesn't bite on Fridays.
  • UIs I don’t want to gouge my eyes over (rarely).

The philosophy I share is "Given proper time, a running laptop, I'd prefer for a Mac, and Stack Overflow, I can do anything.".

\`\`\`
`;

  fs.writeFileSync("README.md", readme);
  console.log("README.md updated, congratulations, congratulations.");
};

generateREADME();
